# Generated by Django 5.2 on 2025-12-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
